"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Image as ImageIcon, Video, Eraser, Brain, QrCode } from "lucide-react";
import TopNavbar from "@/components/TopNavbar";
import Footer from "@/components/Footer";
import Loader from "@/components/Loader";
import { useState, useEffect } from "react";

const tools = [
  {
    name: "Image Remover",
    description: "Remove watermarks from Gemini and Imagen images losslessly.",
    icon: ImageIcon,
    href: "/image-remover",
    color: "from-blue-600 to-blue-500",
  },
  {
    name: "Video Remover",
    description: "Clean invisible watermarks from Sora AI-generated videos.",
    icon: Video,
    href: "/video-remover",
    color: "from-fuchsia-600 to-fuchsia-500",
  },
  {
    name: "Background Remover",
    description: "Instantly strip backgrounds from any image with high precision.",
    icon: Eraser,
    href: "/background-remover",
    color: "from-emerald-600 to-teal-500",
  },
  {
    name: "AI Image Detector",
    description: "Identify if an image was generated by AI or manipulated.",
    icon: Brain,
    href: "/ai-image-detector",
    color: "from-purple-600 to-pink-500",
  },
  {
    name: "QR Generator",
    description: "Create fully styled QR codes for links, Wi-Fi, contacts, events, SMS, and more.",
    icon: QrCode,
    href: "/qr-code-generator",
    color: "from-cyan-600 to-blue-500",
  },
];

export default function LandingPage() {
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      setMousePosition({ x: e.clientX, y: e.clientY });
      setIsVisible(true);
    };

    const handleMouseLeave = () => {
      setIsVisible(false);
    };

    window.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseleave", handleMouseLeave);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseleave", handleMouseLeave);
    };
  }, []);

  return (
    <main className="min-h-screen relative bg-black text-white selection:bg-fuchsia-500/30 overflow-x-hidden">
      {/* Custom Banana Cursor */}
      <div
        className="fixed pointer-events-none z-50 transition-opacity duration-200"
        style={{
          left: `${mousePosition.x}px`,
          top: `${mousePosition.y}px`,
          opacity: isVisible ? 1 : 0,
          transform: "translate(-50%, -50%)",
        }}
      >
        <img
          src="/Banana.webp"
          alt="banana cursor"
          className="w-8 h-8 drop-shadow-lg"
          draggable={false}
        />
      </div>

      <TopNavbar />

      {/* Hero Section Background */}
      <section className="pt-44 md:pt-40 pb-24 px-6 relative">
        {/* Background Gradients */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-3xl h-[400px] opacity-20 pointer-events-none">
          <div
            className="absolute inset-0 blur-[100px] rounded-full mix-blend-screen animated-gradient"
          />
        </div>

        {/* Dashed Grid Background */}
        <div
          className="absolute inset-0 z-0 pointer-events-none"
          style={{
            backgroundImage: `
              linear-gradient(to right, #a9a7a93d 1px, transparent 1px),
              linear-gradient(to bottom, #9d9ea037 1px, transparent 1px)
            `,
            backgroundSize: "20px 20px",
            backgroundPosition: "0 0, 0 0",
            maskImage: `
              repeating-linear-gradient(
                to right,
                black 0px,
                black 3px,
                transparent 3px,
                transparent 8px
              ),
              repeating-linear-gradient(
                to bottom,
                black 0px,
                black 3px,
                transparent 3px,
                transparent 8px
              ),
              radial-gradient(ellipse 70% 60% at 50% 0%, #000 60%, transparent 100%)
            `,
            WebkitMaskImage: `
              repeating-linear-gradient(
                to right,
                black 0px,
                black 3px,
                transparent 3px,
                transparent 8px
              ),
              repeating-linear-gradient(
                to bottom,
                black 0px,
                black 3px,
                transparent 3px,
                transparent 8px
              ),
              radial-gradient(ellipse 70% 60% at 50% 0%, #000 60%, transparent 100%)
            `,
            maskComposite: "intersect",
            WebkitMaskComposite: "source-in",
          }}
        />

        <div className="relative z-10 max-w-7xl mx-auto flex flex-col items-center">
          {/* Hero Section */}
          <div className="text-center max-w-5xl mx-auto mb-20">
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="mb-8 font-serif text-center leading-[0.95] tracking-tight"
            >
              <span 
                className="block whitespace-nowrap font-bold bg-clip-text text-transparent text-[clamp(2.2rem,6.5vw,5.8rem)]"
                style={{
                  backgroundImage: "linear-gradient(to right, #ff6b6b 0%, #ffd93d 25%, #ff9e3d 50%, #ff6ec7 75%, #c77dff 100%)",
                  backgroundClip: "text",
                  WebkitBackgroundClip: "text"
                }}
              >
                Clean. Detect. Generate.
              </span>
              <span className="mt-3 flex items-center justify-center gap-4 text-white text-[clamp(1.85rem,4.9vw,4.2rem)]">
                <span>In Seconds.</span>
                <span className="relative flex items-center justify-center w-[60px] h-[60px]">
                  <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                    <Loader />
                  </div>
                </span>
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="text-base md:text-[1.05rem] text-gray-400 mb-10 max-w-3xl mx-auto leading-relaxed"
            >
              RemoveBanana is an all-in-one toolkit that removes the hard parts, so you can clean, detect, and generate in seconds.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="flex flex-col items-center"
            >
              <a
                href="https://peerlist.io/aashuu/project/removebanana"
                target="_blank"
                rel="noreferrer"
                className="inline-block hover:scale-[1.02] transition-transform shadow-[0_0_30px_rgba(0,0,0,0.5)] rounded-xl"
                aria-label="RemoveBanana on Peerlist"
              >
                <img
                  src="https://peerlist.io/api/v1/projects/embed/PRJHNN7JQ6QA9KKLJ1OA9AK8O9AQP8?showUpvote=true&theme=dark"
                  alt="RemoveBanana"
                  style={{ width: "auto", height: "72px" }}
                />
              </a>
            </motion.div>
          </div>

          {/* Tools Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="w-full max-w-5xl mx-auto"
          >
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-semibold tracking-tight text-white mb-4">
                Explore All Tools
              </h2>
              <div className="w-20 h-1.5 bg-gradient-to-r from-blue-500 via-purple-500 to-fuchsia-500 mx-auto rounded-full opacity-80" />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8">
              {tools.map((tool, index) => {
                const isOddLastCard = tools.length % 2 === 1 && index === tools.length - 1;

                return (
                <Link
                  key={tool.name}
                  href={tool.href}
                  className={`block w-full ${isOddLastCard ? "md:col-span-2 md:mx-auto md:max-w-[calc(50%-1rem)]" : ""}`}
                >
                  <div className="group relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.03] backdrop-blur-sm p-8 hover:bg-white/[0.08] transition-all duration-300 transform hover:-translate-y-1.5 hover:shadow-[0_20px_40px_-15px_rgba(0,0,0,0.7)] hover:border-white/20 h-full flex flex-col justify-between">
                    <div className="absolute -top-10 -right-10 p-6 opacity-[0.03] group-hover:opacity-10 group-hover:scale-125 group-hover:rotate-12 transition-all duration-700 pointer-events-none">
                      <tool.icon className="w-64 h-64" />
                    </div>

                    <div className="relative z-10">
                      <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${tool.color} flex items-center justify-center mb-6 shadow-lg shadow-black/50 group-hover:scale-110 group-hover:rotate-3 transition-transform duration-300`}>
                        <tool.icon className="w-7 h-7 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-white mb-3 group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-gray-300 transition-colors">
                        {tool.name}
                      </h3>
                      <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                        {tool.description}
                      </p>
                    </div>
                    <div className="relative z-10 mt-8 flex items-center font-semibold text-white/60 group-hover:text-white transition-colors">
                      Try it out <span className="ml-2 group-hover:translate-x-1.5 transition-transform">→</span>
                    </div>
                  </div>
                </Link>
              );
              })}
            </div>
          </motion.div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
