"use client";

import { motion } from "framer-motion";
import TopNavbar from "@/components/TopNavbar";
import Footer from "@/components/Footer";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export default function Blog() {
  const posts = [
    {
      id: "remove-gemini-watermark",
      title: "How to Remove Gemini Watermark from AI Images (2026 Guide)",
      excerpt:
        "Google embeds invisible SynthID watermarks into every image generated by Gemini, Imagen 2, and Imagen 3. Learn how to remove them completely — for free, in seconds.",
      date: "March 2026",
      readTime: "8 min read",
    },
    {
      id: "remove-sora-watermark",
      title: "How to Remove Sora Watermark & Download Videos Without Watermark (2026)",
      excerpt:
        "OpenAI Sora adds visible watermark overlays to shared videos. Discover how to download the original clean MP4 file directly from the CDN.",
      date: "March 2026",
      readTime: "7 min read",
    },
    {
      id: "imagen-watermark-removal",
      title: "Remove Google Imagen 2 & Imagen 3 Watermarks from Generated Images",
      excerpt:
        "Google's Imagen models embed the same SynthID watermarks as Gemini. This comprehensive guide shows you how to clean Imagen images in seconds.",
      date: "March 2026",
      readTime: "8 min read",
    },
    {
      id: "qr-code-generator",
      title: "QR Code Generator: Create Styled QR Codes for Any Use Case",
      excerpt:
        "Generate QR codes for URLs, Wi-Fi, vCards, events, SMS, phone, and geo with gradients, logo upload, randomizer, and multi-format exports.",
      date: "March 2026",
      readTime: "6 min read",
    },
  ];

  return (
    <main className="min-h-screen bg-black text-white overflow-x-hidden">
      <TopNavbar />

      <section className="pt-32 pb-20 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mb-16"
          >
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-white mb-6">
              Blog
            </h1>
            <p className="text-xl text-gray-400">
              Learn how to remove AI watermarks and get the most out of Enough Aashuu.
            </p>
          </motion.div>

          <div className="grid gap-8">
            {posts.map((post, index) => (
              <motion.div
                key={post.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
              >
                <Link
                  href={`/blog/${post.id}`}
                  className="group block p-8 rounded-2xl bg-white/5 border border-white/10 hover:border-blue-400/50 hover:bg-white/10 transition-all"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex-1">
                      <h2 className="text-2xl md:text-3xl font-bold text-white group-hover:text-blue-400 transition-colors mb-2">
                        {post.title}
                      </h2>
                      <p className="text-sm text-gray-500">
                        {post.date} · {post.readTime}
                      </p>
                    </div>
                    <ArrowRight className="w-6 h-6 text-gray-400 group-hover:text-blue-400 transition-colors flex-shrink-0 ml-4 mt-1" />
                  </div>
                  <p className="text-gray-400 text-lg leading-relaxed">{post.excerpt}</p>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
